name: Laravel Testing

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP with logs
        uses: shivammathur/setup-php@verbose
        with:
          php-version: '7.4'

      - name: Report PHP version
        run: php -v

      - name: Copy .env Laravel Configuration for CI
        run: php -r "file_exists('site/.env') || copy('.env.example', '.env');"
        working-directory: ./site

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer install
        working-directory: ./site

      - name: Generate key
        run: php artisan key:generate
        working-directory: ./site

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
        working-directory: ./site

      - name: Create Database
        run: |
          mkdir -p site/database
          touch site/database/database.sqlite

      - name: Execute tests (Unit and Feature tests) via PHPUnit
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: php artisan test --parallel
        working-directory: ./site

      - name: FreshMigrate + Seed
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: php artisan devtool:freshmigrate
        working-directory: ./site
