name: Laravel

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Setup PHP with logs
      uses: shivammathur/setup-php@verbose
      with:
        php-version: '7.4'
    - uses: actions/checkout@v2
    - name: Report PHP version
      run: php -v
    - name: Copy .env
      run: php -r "file_exists('site/.env') || copy('site/.env.example', 'site/.env');"
    - name: Install Dependencies
      run: cd site && composer install
    - name: Generate key
      run: cd site && php artisan key:generate
    - name: Directory Permissions
      run: cd site &&  chmod -R 777 storage bootstrap/cache
    - name: Create Database
      run: |
        mkdir -p site/database
        touch site/database/database.sqlite
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: cd site && vendor/bin/phpunit
    - name: FreshMigrate + Seed
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: cd site && php artisan devtool:freshmigrate
