version: '3'
services:

  service:
    build:
      context: ./docker/php7.4.19-apache-buster-dev
    image: bac:service
    container_name: service
    hostname: service
    restart: unless-stopped
    environment:
      - TZ=Etc/UTC
    working_dir: /var/www
    extra_hosts:
      - "bacapi.local:${WEBSERVER_IP}"
    volumes:
      - "./../site/:/var/www/"
      - "./etc/php/local.ini:/usr/local/etc/php/conf.d/local.ini"
      - "./etc/apache/000-default.conf:/etc/apache2/sites-enabled/000-default.conf"
      - "./etc/supervisor/:/etc/supervisor/conf.d/"
    ports:
      - "8081:80"
    expose:
      - 80
    networks:
      bac-network:
        ipv4_address: ${SERVICE_IP}

#Docker Networks
networks:
  bac-network:
    external: true

#networks:
#  app-network:
#    driver: bridge
